# Bash init script for my mac.
# Mohit Cheppudira <mohit@muthanna.com>

source $EVIL_HOME/dotfiles/bashrc.include.sh

# Use x11 as the default Gnuplot/Octave terminal
export GNUTERM=x11

# Bash completion (brew install bash_completion)
[ -f ~/homebrew/etc/bash_completion ] && . ~/homebrew/etc/bash_completion

setup_common

export PATH=~/bin:$EC2_HOME/bin:/opt/local/bin:/opt/local/sbin:~/golang/bin:$PATH
